version: "3.3"

services:

  db:
    restart: always
    image: postgres
    container_name: demo-postgres
    environment:
      - POSTGRES_USER=ankush
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - /mnt/postgres-data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ankush@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        - /mnt/pgadmin-data:/var/lib/pgadmin
      restart: always
