# Generated by Django 3.2.6 on 2021-08-14 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('editors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
