# Generated by Django 3.2.6 on 2021-08-16 12:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('todo', '0001_initial'), ('todo', '0002_auto_20210814_1257'), ('todo', '0003_todo_status'), ('todo', '0004_auto_20210816_0523'), ('todo', '0005_alter_todo_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('editors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('inprogress', 'inprogress')], default='inprogress', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
