# Generated by Django 3.2.6 on 2021-08-17 05:52

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('todo', '0001_0001_to_0005_migrations_squashed'), ('todo', '0002_auto_20210817_0424')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('inprogress', 'inprogress')], default='inprogress', max_length=20)),
                ('editors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
