# Generated by Django 3.2.6 on 2021-08-14 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
