# Generated by Django 3.2.6 on 2021-08-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210814_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('inprogress', 'inprogress')], default='inprogress', max_length=20),
        ),
    ]
